---
- hosts: all
  sudo: true
  roles:
    - {role: docker, docker_options: "--selinux-enabled -H tcp://localhost:2375", docker_host: "tcp://localhost:2375", docker_registry_certificates: "/etc/docker/certs.d/registry.jufis.net:443", docker_registry_path: "registry.jufis.net:443"}
    - {role: docker-rest-client, server_name: "server", server_ip: "192.168.1.7", docker_host: "tcp://localhost:2375", docker_registry_location: "registry.jufis.net:443", docker_application_name: "docker-rest-client", git_tag: "latest", docker_registry_name: "registry.jufis.net", docker_registry_ip: "192.168.1.7", docker_repository: "jufis-dev"}
