---
- hosts: all
  sudo: true
  roles:
    - {role: docker, docker_options: "--tlsverify --tlscacert=/root/.docker/ca.pem --tlscert=/root/.docker/server-cert.pem --tlskey=/root/.docker/server-key.pem -H=tcp://localhost:2376", docker_host: "tcp://docker.jufis.net:2376", docker_registry_certificates: "/etc/docker/certs.d/registry.jufis.net:443", docker_registry_path: "registry.jufis.net:443", docker_client_certificates: "/home/jufis/.docker/"}
    - {role: docker-rest-client, server_name: "server", server_ip: "192.168.1.7", docker_host: "tcp://docker.jufis.net:2376", docker_registry_location: "registry.jufis.net:443", docker_application_name: "docker-rest-client", git_tag: "latest", docker_registry_name: "registry.jufis.net", docker_registry_ip: "192.168.1.7", docker_repository: "jufis-dev", docker_server: "docker.jufis.net"}
